apiVersion: v1
kind: Pod
metadata:
  name: nodeserver
  labels:
    app: nodeserver
spec:
  containers:
    - name: nodeserver
      image: felipeken/node-k8s:latest
      ports:
        - containerPort: 3000